### ISSUE TITLE
Suggested method for username/password implementation?

### ISSUE THREAD

**Issue by kristojorg** [microauth/microauth#1]

**Comment by dimapaloskin** [comment]
Honestly I don't know what we need to implement for this method :) There are no very common approach for this type of method.
For example it's can looks like:
```js
const { username, password } = json(req);
if (username === userNameFromDb && crypto(password) === passwordFromDb) {
  // ...
}
```

I don't have any idea how it's can be simplified and what hight level interface we can provide. Do you have any suggestions?

**Comment by kristojorg** [comment]
Not sure either, haven't ever implemented auth before now so I'll have to figure it out. I'll let you know what I end up with and if I think it could be incorporated : )

**Comment by dimapaloskin** [comment]
I guess this issue can be closed :)
