### ISSUE TITLE
Moving microauth-google into microauth org

### ISSUE THREAD

**Issue by rapzo** [microauth/microauth#4]
Just a noob question: will i have ownership for the repo cause i have some changes on the way.

**Comment by dimapaloskin** [comment]
I added you into organization so now you can create repositories.
You need use "Transfer ownership" button on the repo settings page.
Now you should have access to all `microauth` repositories. Let's check it :)

**Comment by dimapaloskin** [comment]
When you transfer your repository into organization, you will keep all ownership privileges, for sure. It's just more useful when all `microauth` repositories keeping in a common organization.
